version: '3.7'
services:
  app:
    build:
      args:
        - install_dev_packages=true
      context: .
      cache_from:
        - popcodeorg/popcode:latest
    command: npm start
    ports:
      - '3000:3000'
      - '3001:3001'
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
      - bower_components:/app/bower_components
      - npm_cache:/root/.npm
      - yarn_cache:/usr/local/share/.cache/yarn
    tmpfs:
      - /app/dist
    environment:
      - DEBUG
      - PROFILE_BUILD
volumes:
  npm_cache:
  node_modules:
  bower_components:
  yarn_cache:
